---
- name: Create flux-system namespace
  hosts: localhost

  tasks:
  - name: Create namespace
    kubernetes.core.k8s:
      api_version: v1
      kind: Namespace
      name: flux-system
      state: present